title: "Zetsus Objektive Sichtweise"
author: "Zetsu"
description: "Ein Ort, an dem ich meine Erkenntnisse und Erfahrungen über Programmierung und andere autistische Themen niederschreiben kann"

email: "zetsuboushii@gmail.com"
github_username: "zetsuboushii"
instagram_username: "zetsuboushii"

theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: false
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
